# Use the official Python image as base
FROM python:3.9-slim
# Set the working directory inside the container
WORKDIR /2-simpleApp
# Copy the application file from the host to the container's working directory
COPY app.py .
# Define the default command to run the application when the container starts
CMD ["python", "app.py"]

